spring:
  database:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialectct
  datasource:
    plataform: postgres
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 12333
  servlet:
    context-path: /geduca