spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_geduca?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: null
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-ignored-properties: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 12333
  servlet:
    context-path: /geduca